version: "3.5"

services:
  php_fpm:
      build: .
      container_name: football_php_fpm
      working_dir: /usr/share/nginx/football
      networks:
        - football
      volumes:
          - ./:/usr/share/nginx/football

  nginx:
      image: nginx:1.15
      container_name: football_nginx
      working_dir: /usr/share/nginx/football
      networks:
        - football
      ports:
          - "8080:80"
      volumes:
          - ./:/usr/share/nginx/football
          - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  mysql:
      image: mysql:5.7
      container_name: football_mysql
      networks:
        - football
      environment:
        - MYSQL_DATABASE=football
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_USER=football
        - MYSQL_PASSWORD=password

networks:
  football:
    driver: bridge
